# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------
template = lib

HEADERS += $$PWD/plugin.h \
    $$PWD/memorymanager.hpp
SOURCES += $$PWD/memorymanager.cpp \
    $$PWD/plugin.cpp
