# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------
TEMPLATE = lib
TARGET = autolink_plugin

HEADERS += plugin.h \
    memorymanager.hpp
SOURCES += memorymanager.cpp \
    plugin.cpp
